- bot_name: 'bot_auto_trans'
  bot_params:
    tran_amount: 0.0001
    when_ever: 20s
  bot_data_channels:
    - 'bter'
    - 'hex'
    - 'okcoin'
  bot_markets:
    - id: btccny
      name: BTC/CNY
      base_unit: btc
      quote_unit: cny
      tran_price_add: 0.1
      tran_amount: 0.0001
    - id: ethcny
      name: ETH/CNY
      base_unit: eth
      quote_unit: cny
      tran_price_add: 0.1
      tran_amount: 0.0001
    - id: btceth
      name: BTC/ETH
      base_unit: btc
      quote_unit: eth
      tran_price_add: 0.1
      tran_amount: 0.0001
    - id: ethbtc
      name: ETH/BTC
      base_unit: eth
      quote_unit: btc
      tran_price_add: 0.1
      tran_amount: 0.0001